name: bq32000
description: Driver for BQ32000
version: 1.0.0
groups:
  - rtc
code_owners: HoangBui
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: HoangBui
    year: 2025
